; PlatformIO Project Configuration File for WiFiManager Library
; This file is used for building tests

[env:esp8266]
platform = espressif8266
board = d1_mini
framework = arduino
monitor_speed = 115200
test_framework = unity
test_build_src = no
lib_deps = 
    ESP32Async/ESPAsyncWebServer@3.9.1
    https://github.com/alexhopeoconnor/DFTE

[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
test_framework = unity
test_build_src = no
build_unflags = 
    -std=gnu++11
build_flags = 
    -std=gnu++14
lib_deps = 
    ESP32Async/ESPAsyncWebServer@3.9.1
    https://github.com/alexhopeoconnor/DFTE

