; PlatformIO Project Configuration File for WiFiManager Library
; This file is used for building tests

[env:esp8266]
platform = espressif8266
board = d1_mini
framework = arduino
monitor_speed = 115200
test_framework = unity
test_build_src = no

[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
test_framework = unity
test_build_src = no

